services:
  - type: web
    name: bookstore-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/products/
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: bookstore-api.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"